export enum RouteEnum {
    ALL = '*',
    LOGIN = '/login',
    LANDING = '/',
    HOME = '/home',
    BROWSE = '/browse',
    CREATE_POST = '/create-post',
    POST = '/post/:id',
    PROFILE = '/profile',
    EDIT_PROFILE = '/edit-profile',
    BORROWER = '/borrower',
    TRANSACTION_HISTORY = '/transaction-history',
    POST_VERIFICATION = '/post-verification',
    ABOUT = '/about',
}